//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

pub use super::article::Entity as Article;
pub use super::link::Entity as Link;
pub use super::mikro_orm_migrations::Entity as MikroOrmMigrations;
pub use super::user::Entity as User;
